<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <!-- xunit v3: тестовый проект — исполняемый файл -->
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <RootNamespace>Anitools.App.Tests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Avalonia.Headless.XUnit" />
    <PackageReference Include="Avalonia.Skia" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Anitools.App\Anitools.App.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <Compile Include="..\Shared\*.cs" LinkBase="Shared" />
  </ItemGroup>

</Project>
