#!/usr/bin/env python3
"""
Таблица для PyText.CaseFold: символы, у которых str.casefold() в Python отличается от str.lower()
(ß → ss, ſ → s, ﬁ → fi, греческие буквы с подписной йотой, …). Остальное C# берёт из lower().

    python3 tools/gen_casefold.py   # пишет src/Anitools.Core/Parsing/PyText.CaseFold.g.cs
"""
import sys
import unicodedata
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "src" / "Anitools.Core" / "Parsing" / "PyText.CaseFold.g.cs"


def cs_string(s: str) -> str:
    return '"' + "".join(f"\\u{ord(c):04X}" if ord(c) < 0x10000 else f"\\U{ord(c):08X}" for c in s) + '"'


def main() -> int:
    rows = []
    for cp in range(sys.maxunicode + 1):
        if 0xD800 <= cp <= 0xDFFF:
            continue
        c = chr(cp)
        if c.casefold() != c.lower():
            rows.append(f"        [0x{cp:04X}] = {cs_string(c.casefold())},")
    text = "\n".join([
        "// <auto-generated>",
        f"// tools/gen_casefold.py, Python {sys.version.split()[0]}, Unicode {unicodedata.unidata_version}.",
        "// Не править руками.",
        "// </auto-generated>",
        "using System.Collections.Frozen;",
        "",
        "namespace Anitools.Core.Parsing;",
        "",
        "internal static partial class PyText",
        "{",
        "    /// <summary>Символы, у которых str.casefold() отличается от str.lower().</summary>",
        "    private static readonly FrozenDictionary<int, string> CaseFoldExceptions = new Dictionary<int, string>",
        "    {",
        *rows,
        "    }.ToFrozenDictionary();",
        "}",
        "",
    ])
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print(f"{len(rows)} символов → {OUT.relative_to(OUT.parents[3]).as_posix()}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
